### ISSUE TITLE
Fastlane in Android

### ISSUE THREAD

**Issue by Tohure** [Android-Dev-Peru/propuestas-meetup#25]
¿Cansado del largo, trabajoso y fastidioso proceso de deployar a tienda tu aplicación?. ¡Fastlane al rescate!

Compilando y Deployando App's desde la línea de comandos!

**Comment by jchoy8890** [comment]
Hola Carlo, ¿podrías dejarme tu número de celular para poder contactarme contigo? Necesitamos coordinar para tu propuesta para el meetup.

Gracias.
