### ISSUE TITLE
Android Things #workshop

### ISSUE THREAD

**Issue by carlosgub** [Android-Dev-Peru/propuestas-meetup#27]
Mostrare un ejemplo de un como realizar un cuarto inteligente con el developer kit entregado en Google I/O o con un raspberry Pi 3 Model B mediante el uso de Firebase y un relay.

Firebase -> Se usara para modificar el estado de los focos, ventiladores, etc.

Relay -> Sera el interruptor que nos ayudara a hacer que pase o bloquear la electricidad de la casa.

![27115](https://user-images.githubusercontent.com/30916886/43684468-533072d0-9866-11e8-92b7-315b91255339.png)

Kit Android Things
![43680743-8037eaac-9806-11e8-9111-aacbda13fa05](https://user-images.githubusercontent.com/30916886/43684482-8f7f67be-9866-11e8-840b-54530a48017c.png)

Repo donde esta todo explicado :D: https://github.com/carlosgub/Cuarto-Inteligente-Repo

PD: Hice repost porque me equivoque de cuenta :D

label

**Comment by jchoy8890** [comment]
Hola Carlos, ¿podrías dejarme tu número de celular para poder contactarme contigo? Necesitamos coordinar para tu propuesta para el meetup.

Gracias.

**Comment by carlosgub** [comment]
994782277 :D
