### ISSUE TITLE
ML Kit Face Detection

### ISSUE THREAD

**Issue by carlosgub** [Android-Dev-Peru/propuestas-meetup#28]
Mostrare un ejemplo de como implementar la libreria de Firebase de Machine Learning de deteccion de caras para Android. Donde este ejemplo puede detectar imagenes tomadas desde el propio telefono o seleccionando alguna de la galeria del celular.

Al momento reconocer la cara, se dibuja un cuadrado en la superficie y dibuja ademas los puntos señalando los ojos, labio derecho, labio izquierdo, etc.

gif: https://imgur.com/a/rQdoEoV

Repositorio: https://github.com/carlosgub/MLKit-Face-Example

**Comment by jnolascob** [comment]
Confirmado para el meetup #19
