### ISSUE TITLE
How to build a video app

### ISSUE THREAD

**Issue by DanP1925** [Android-Dev-Peru/propuestas-meetup#38]
Describir y mostrar como organizar una aplicacion de media segun la arquitectura que google recomienda (https://developer.android.com/guide/topics/media-apps/media-apps-overview). Se usaria como ejemplo una aplicacion de video (https://developer.android.com/guide/topics/media-apps/video-app/building-a-video-app). Podria explicar que ventajas tiene organizar el codigo de esta manera y como ha sido implementar esto en mi trabajo.

**Comment by jflavio11** [comment]
Hola, @DanP1925:

Por favor, colocar un medio de contacto, please

Thanks! 🤓

**Comment by jflavio11** [comment]
Confirmado para MeetUp#25
https://www.meetup.com/es-ES/Android-Dev-Peru/events/266165242/
