### ISSUE TITLE
 Android Development Tools 

### ISSUE THREAD

**Issue by deanayac** [Android-Dev-Peru/propuestas-meetup#39]
# Título de tu charla o workshop 
 Android Development Tools 
#### Tipo de evento
[X] Charla
[ ] Workshop
#### Descripción corta
Esta charla sera una recopilación de buenas practicas y herramientas que un desarrollador mobile debe tener en cuenta para empezar su carrera como desarrollador y compartir experiencias de otros developers.

#### Medio de contacto
Puedes dejar tu email o teléfono celular

_No olvidar etiquetar el issue con "talk" o "workshop"_

**Comment by jflavio11** [comment]
Confirmado para el MeetUp #26
https://www.meetup.com/es-ES/Android-Dev-Peru/events/268122488/
