### ISSUE TITLE
Developing a Fan Made Version on my University's App

### ISSUE THREAD

**Issue by Bruno125** [Android-Dev-Peru/propuestas-meetup#4]
[Nombre de la charla por definir]

Hablaría un poco acerca de esto cómo desarrollé una aplicación para mi universidad:

https://medium.com/@bruno.aybar/developing-a-fan-made-version-of-my-universitys-app-9eec3baafcd3

A diferencia del post, en el cual traté de no profundizar mucho, en la charla desarrollaría mucho más los temas técnicos, como por ejemplo:

- Decompilación de APKs
- Definición de requerimientos e historias de usuario
- Prototipado de apps
- Integración de herramientas de analítica
- Tecnologías y patrones que utilicé

**Comment by hacksy** [comment]
Esta interesante tu charla ... no se que tan seguro es hablar de la decompilación del APK , considerando leyes peruanas .
https://www.indecopi.gob.pe/documents/20182/143803/GDA_CreadoresDeSoftware.pdf (punto 26)

**Comment by Bruno125** [comment]
Qué maestro! Estaba buscando algo así pero no encontraba. Creo que en ese caso sería incluso más importante hablar del tema. 

Del lado del desarrollador: Por un lado, querramos o no, las aplicaciones que desarrollamos siempre podrán ser decompiladas y debemos tomar las medidas necesarias para protegernos contra esto

Del lado del decompilador (?): sabemos que se puede hacer, no quiere decir que sea correcto que nosotros lo hagamos en cualquier cosa, tal como se menciona en el punto en el que mencionas. Es posible que muchos no los sepan (como yo cuando hice el app).

De lo que leí en ese artículo -me parece- que lo que yo hice cuenta como "actividades no infractoras de ingeniería inversa realizadas de buena fe" así que no habría problema (aunque podría haberlo entendido todo mal, la terminología legal no es mi especialidad)

**Comment by hacksy** [comment]
Te recomiendo decir al menos, "Esto lo hice con fines educativos y sin intereses economicos" . Ayuda un poco :D
