### ISSUE TITLE
Charla: Tareas repetitivas y programadas en Android

### ISSUE THREAD

**Issue by josemgu91** [Android-Dev-Peru/propuestas-meetup#40]
# Tareas repetitivas y programadas en Android 

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
Métodos (y desafíos) para ejecutar rutinas de forma repetitiva (Java Timer, Android Handler, etc.) o programada (AlarmManager, JobScheduler, WorkManager, etc.) en Android.

#### Medio de contacto
josemgu91@gmail.com

#### Notas adicionales
No antes de Abril del 2020.

**Comment by jflavio11** [comment]
Pendiente para confirmación del MeetUp de Abril
