### ISSUE TITLE
Charla: The Apps Re-engagement Challenge: App Actions

### ISSUE THREAD

**Issue by Tohure** [Android-Dev-Peru/propuestas-meetup#41]
# The Apps Re-engagement Challenge: _App Actions_

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
App Actions proporciona una forma más rápida para que los usuarios accedan a nuestras aplicaciones Android a través de Google Assistant

#### Medio de contacto
941930244

 _talk_

**Comment by jflavio11** [comment]
Confirmado para MeetUp #27

**Comment by jflavio11** [comment]
Link a MeetUp:
https://www.meetup.com/es-ES/Android-Dev-Peru/events/269631831/

Charla en Youtube:
https://www.youtube.com/watch?v=wbBrx5iv4RY
