### ISSUE TITLE
Charla: How to automate code reviews with static analysis tools

### ISSUE THREAD

**Issue by DanP1925** [Android-Dev-Peru/propuestas-meetup#42]
# How to automate code reviews with static analysis tools

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
Explicaré qué es un code review y sus ventajas. 
Luego introduciré unas herramientas que ayuden a automatizar el proceso de revision de formato, estilos y test coverage como por ejemplo **detekt** [https://github.com/arturbosch/detekt] y **ktlint** [https://github.com/pinterest/ktlint].
Por último indicaré a grandes rasgos que cosas si deberían tener una revisión manual en los code reviews (si hay casos que no cubren las pruebas, si se puede utilizar la bd local en vez de una llamada un servicio, etc...) basado en el libro **What to look for in a Code Review** [https://blog.jetbrains.com/upsource/2016/01/25/what-to-look-for-in-a-code-review-book/]

#### Medio de contacto
DanP1925@gmail.com

**Comment by jflavio11** [comment]
Confirmado para MeetUp #27

**Comment by jflavio11** [comment]
Link a MeetUp:
https://www.meetup.com/es-ES/Android-Dev-Peru/events/269631831/

Charla en Youtube:
https://www.youtube.com/watch?v=wbBrx5iv4RY
