### ISSUE TITLE
Charla: Persistencia de datos con Room

### ISSUE THREAD

**Issue by bsoto24** [Android-Dev-Peru/propuestas-meetup#44]
# Charla: Persistencia de datos con Room

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
Explicaré cómo almacenar datos estructurados en nuestro dispositivo implementando Room, las ventajas de utilizar esta librería, como diseñar e implementar nuestra base de datos, el uso de anotaciones, como manejar tipos de dato especiales y realizar migraciones.

#### Medio de contacto
bsoto.dev@gmail.com

_No olvidar etiquetar el issue con "talk" o "workshop"_

**Comment by jflavio11** [comment]
Confirmado para el MeetUp #29!
