### ISSUE TITLE
Charla: Título de la charla

### ISSUE THREAD

**Issue by Naibeck** [Android-Dev-Peru/propuestas-meetup#48]
# Getting Started Jetpack Compose

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
Presentación de como utilizar Jetpack Compose para crear diferentes UI.

#### Medio de contacto
kg-diseno@outlook.es
+598098377662 (Whatsapp o Telegram)

_No olvidar etiquetar el issue con "talk" o "workshop"_

**Comment by emedinaa** [comment]
Gracias @Naibeck  !!
