### ISSUE TITLE
Charla: Kotlin Multiplatform by example

### ISSUE THREAD

**Issue by camachoyury** [Android-Dev-Peru/propuestas-meetup#49]
# Kotlin Multiplatform by example

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
a pesar de que KMP esta en etapa experimental , muchas empresas ya la están usando es por esa razón que en esta charla se hablara de como implementar KMP  

#### Medio de contacto
Puedes dejar tu email o teléfono celular
camachoyury@gmail.com 

_No olvidar etiquetar el issue con "talk" o "workshop"_

**Comment by emedinaa** [comment]
gracias ! @camachoyury
