### ISSUE TITLE
Charla: Crea tu lector de QR con CameraX

### ISSUE THREAD

**Issue by carlosgub** [Android-Dev-Peru/propuestas-meetup#57]
# Título de tu charla o workshop 

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
Se mostrara como crear un lector de QR con CameraX usando ML Kit de Firebase

#### Medio de contacto
Email: carlosgabrielugazburga@gmail.com

**Comment by jflavio11** [comment]
¡Gracias por tu participación en el MeetUp de noviembre del 2020!
https://www.meetup.com/es-ES/Android-Dev-Peru/events/274749253/
