### ISSUE TITLE
Charla: Realidad Aumentada Nativa con ARCore

### ISSUE THREAD

**Issue by giancarlodcp** [Android-Dev-Peru/propuestas-meetup#59]
# Realidad Aumentada Nativa con ARCore

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
Una charla sobre como comenzar a usar ARCore sin morir en el intento y porque es mejor que muchas plataformas de realidad aumentada. Hablaremos de como crear un proyecto con ARCore, usaremos el ARFaces para ponernos un gorrito de mario bros y mostraré una demo de como hacer una tienda virtual de objetos 3D y veremos una arquitectura escalable para proyectos de gran envergadura. 

#### Medio de contacto
giancarlocalderonp@gmail.com
947736077 - Lima
### Imágenes
![tigre](https://user-images.githubusercontent.com/71103151/99009582-3f832680-2516-11eb-82f7-37af04922a71.png)

![Screenshot_20200124_214311_com stickstudios augmentedfaces](https://user-images.githubusercontent.com/71103151/99008862-00080a80-2515-11eb-8e29-9f4503cec0de.jpg)

**Comment by emedinaa** [comment]
Gracias por tu participación en el meetup !
