### ISSUE TITLE
Charla: Android Associate Developer, como no morir en el intento

### ISSUE THREAD

**Issue by josemiZ** [Android-Dev-Peru/propuestas-meetup#65]
# Android Associate Developer, como no morir en el intento

#### Tipo de evento
[X] Charla
[ ] Workshop

#### Descripción corta
En esta charla hablaremos de cómo lograr el tan aclamado Android Associate Developer, por donde empezar, que estudiar, por qué hacerlo y sobre todo cuánto cuesta y cuántas oportunidades tenemos.

#### Medio de contacto
mail: jzeaguerrero@gmail.com
telefono: +51957792143

**Comment by Bruno125** [comment]
✅ presentada en el meetup agosto 2023
