### ISSUE TITLE
Charla: Librería PreCompose para Kotlin Multiplatform

### ISSUE THREAD

**Issue by andres04** [Android-Dev-Peru/propuestas-meetup#67]
# Librería PreCompose para Kotlin Multiplatform
#### Tipo de evento
[X] Charla
[] Workshop

#### Descripción corta
En esta presentación abordaremos el uso de la librería PreCompose, una potente herramienta que brinda la capacidad de usar ViewModels y Navigation en Kotlin Multiplataform y también veremos su integración con Koin, Por último se hará una demo virtual para correrlo en Android, Desktop y ios. 

#### Medio de contacto
correo: andresescobarvilla@gmail.com 
telf: 985038537

_No olvidar etiquetar el issue con "talk" o "workshop"_

**Comment by pedrorau** [comment]
✅ presentada en el meetup enero 2024
