### ISSUE TITLE
Custom Views & ViewGroups

### ISSUE THREAD

**Issue by Bruno125** [Android-Dev-Peru/propuestas-meetup#8]
- Veremos cuál es la lógica detrás del renderizado de las vistas 
- Para qué sirven los métodos onMeasure, onLayout, onDraw, etc? Qué es un MeasureSpec?
- Cuando utilizar custom Views / ViewGroups?

**Comment by jordanchba** [comment]
Me encanta este tema seria demasiado interesante

**Comment by Bruno125** [comment]
Hola @jordanchba, esta charla la dicta hace ya unos meses :( Pero puedes encontrar las diapos aqui: https://speakerdeck.com/bruno125/android-custom-views
